version: "3.8"

services:
    permission_guide-postgresql:
        image: postgres:latest
        container_name: permission_guide-postgresql
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        networks:
            - permission_guide-postgresql-net
        ports:
            - 65432:5432
        volumes:
            - permission_guide-postgresql-data:/var/lib/postgresql/data


volumes:
    permission_guide-postgresql-data:


networks:
    permission_guide-postgresql-net:
        driver: bridge