version: "3.8"

services:
    permission_guide-postgresql:
        image: postgres:latest
        container_name: permission_guide-postgresql
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        networks:
            - permission_guide-postgresql-net
        ports:
            - 65432:5432
        volumes:
            - permission_guide-postgresql-data:/var/lib/postgresql/data



    permission_guide-redis:
        image: redis:latest
        container_name: permission_guide-redis
        hostname: redis
        restart: always
        networks:
            - permission_guide-postgresql-net
        ports:
            - "56379:6379"


    permission_guide-redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: permission_guide-redis-commander
        hostname: redis-commander
        restart: always
        networks:
            - permission_guide-postgresql-net
        environment:
            - REDIS_HOSTS=redis
        ports:
            - "58081:8081"
        

volumes:
    permission_guide-postgresql-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: "./data-volume/sql"


networks:
    permission_guide-postgresql-net:
        driver: bridge